config/routes.rb
Gavel::Application.routes.draw do

  get "page/about"
  get "page/contact"
  root 'posts#index'

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'

  resources :users
  resources :posts
  resources :responses
  resources :sessions, only: [:create, :destroy, :new]

  get '/posts/:id/upvote', to: 'posts#upvote', as: 'upvote'
  get '/posts/:id/downvote', to: 'posts#downvote', as: 'downvote'

  get '/admin', to: 'users#index', as: 'admin'

end

app/models/user.rb
class User
  include Mongoid::Document

  before_save :encrypt_password

  has_many :posts, inverse_of: :author
  has_many :responses, inverse_of: :author
  has_and_belongs_to_many :upvotes, class_name: "Post", inverse_of: :upvotes
  has_and_belongs_to_many :downvotes, class_name: "Post", inverse_of: :downvotes

  field :name, type: String, default: ""
  field :email, type: String, default: ""
  field :password, type: String, default: ""
  field :password_salt, type: String, default: ""
  field :password_hash, type: String, default: ""
  field :role, type: String, default: "user"
  field :created_at, type: DateTime, default: -> { Time.now }
  field :last_seen, type: DateTime, default: -> { Time.now }

  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A\w+@\w+.[a-z]{2,}\Z/ }, uniqueness: true
  validates :password_hash, presence: true
  validates :created_at, presence: true
  validates :last_seen, presence: true

  def encrypt_password
    if !password.empty?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      self.password = ""
    end
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first()
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      return user
    else
      return nil
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_access, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:index]
  skip_before_filter :require_user, :only => [:new, :create]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field input-group widen">
    <%= f.label :name, class: 'sr-only' %><br>
    <%= f.text_field :name, class: 'form-control', placeholder: 'name' %>
  </div>
<div class="field input-group widen">
    <%= f.label :email, class: 'sr-only' %><br>
    <%= f.email_field :email, class: 'form-control', placeholder: 'email' %>
  </div>
<div class="field input-group widen">
    <%= f.label :password, class: 'sr-only' %><br>
    <%= f.password_field :password, class: 'form-control', placeholder: 'password' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success widen' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="text-center">
			<h3>Edit:</h3>
			<%= render 'form' %>
		</div>
	</div> <!-- /row -->
</div> <!-- /com-md-8 -->

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Created at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="text-center">
			<h3>Sign up:</h3>
			<%= render 'form' %>
		</div>
	</div> <!-- /row -->
</div> <!-- /com-md-8 -->

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>Your account details:</h3>
				</div>

				<div class="panel-body">
					<h4>
						<strong>Name:</strong> <%= @user.name %>
					</h4>
					<h4>
						<strong>Email:</strong> <%= @user.email %>
					</h4>

					<%= link_to 'Edit your profile', edit_user_url, {class: 'btn btn-primary navbar-btn widen', role: 'button'} %>

				</div>
			</div>
		</div>

		<div class="row">
			<h3>Your posts:</h3>
			<% @user.posts.each do |post| %>
			<div class="row">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="share-tray">
							<ul>
								<li><span class="icomoon icon-facebook3"></span></li>
								<li><span class="icomoon icon-twitter3"></span></li>
							</ul>
						</div>
						<h3>
							<%= post.title %>
						</h3>
						<p>
							<%= post.body %>
						</p>
						<div class="text-right">
							<!-- <a href="/upvote">upvote</a> -->
							<!-- <a href="/upvote">downvote</a> -->
							<%= link_to 'Show', post %>
						</div>
					</div>
				</div>
			</div>
			<% end %>
		</div> <!-- /row -->
	</div> <!-- /com-md-8 -->