config/routes.rb
Gavel::Application.routes.draw do

  get "page/about"
  get "page/contact"
  root 'posts#index'

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'

  resources :users
  resources :posts
  resources :responses
  resources :sessions, only: [:create, :destroy, :new]

  get '/posts/:id/upvote', to: 'posts#upvote', as: 'upvote'
  get '/posts/:id/downvote', to: 'posts#downvote', as: 'downvote'

  get '/admin', to: 'users#index', as: 'admin'

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_user, :only => [:index, :show]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(response_params)
    @response.author = @current_user
    @post = Post.find(params[:post_id])
    @response.post = @post

    respond_to do |format|
      if @response.save
        format.html { redirect_to @post, notice: 'Response was successfully created.' }
        format.json { render action: 'show', status: :created, location: @response }
      else
        format.html { render action: 'new' }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:body, :verdict, :created_at, :updated_at)
    end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
<% if @response.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

  <ul>
    <% @response.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= hidden_field_tag 'post_id', params[:id]  %>
<div class="field input-group widen">
  <%= f.label :body, class: 'sr-only' %><br>
  <%= f.text_area :body, rows: 3, class: 'form-control', placeholder: 'let us know what you think...' %>
</div>
<div class="actions">
  <%= f.submit class: 'btn btn-success widen' %>
</div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <thead>
    <tr>
      <th>Vote count</th>
      <th>Body</th>
      <th>Verdict</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.vote_count %></td>
        <td><%= response.body %></td>
        <td><%= response.verdict %></td>
        <td><%= response.created_at %></td>
        <td><%= response.updated_at %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="text-center">
			<h3>Post a Comment:</h3>
			<%= render 'form' %>
		</div>
	</div> <!-- /row -->
</div> <!-- /com-md-8 -->

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row text-center">
  <h2>
    <%= @response.body %>
  </h2>
</div>