config/routes.rb
Gavel::Application.routes.draw do

  get "page/about"
  get "page/contact"
  root 'posts#index'

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'

  resources :users
  resources :posts
  resources :responses
  resources :sessions, only: [:create, :destroy, :new]

  get '/posts/:id/upvote', to: 'posts#upvote', as: 'upvote'
  get '/posts/:id/downvote', to: 'posts#downvote', as: 'downvote'

  get '/admin', to: 'users#index', as: 'admin'

end

app/views/layouts/_footer.html.erb
<div class="container" id="footer">
<hr>
<footer class="text-center">
	<p>
		<span id="copyright" title="Page Rendered in <%= sprintf('%.3f', (Time.now.usec - @start_time).abs / 1000000.0) %> seconds">&copy;</span>
		<%= link_to 'William Falk-Wallace', 'http://www.falk-wallace.com' %> <%= Time.now.year %>
	</p>
</footer>
</div>

app/views/layouts/_navbar.html.erb
<div class='navbar navbar-fixed-top navbar-default' role='navigation'>
	<div class='container'>
		<div class='navbar-header'>
			<button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
				<span class='sr-only'>Toggle navigation</span>
				<span class='icon-bar'></span>
				<span class='icon-bar'></span>
				<span class='icon-bar'></span>
			</button>
			<%= link_to root_url, class: 'navbar-brand' do %>
			<span class="icomoon icon-hammer2"> Gavel</span>
			<% end %>
		</div>
		<div class='navbar-collapse collapse'>
			<ul class='nav navbar-nav'>
				<li><%= link_to 'About', page_about_url %></li>
				<li><%= link_to 'Contact us', page_contact_url %></li>
			</ul>
			<div class='navbar-right'>
				<% if @current_user.present? %>
				<p class="navbar-text">
					Signed in as <%= link_to @current_user.name, {controller: "users", action: "show", id: @current_user.id}, class: 'navbar-link' %>
				</p>
				<%= link_to 'Make a decision', new_post_url, {class: 'btn btn-primary navbar-btn', role: 'button'} %>
				<%= link_to 'Log out', logout_url, {class: 'btn btn-danger navbar-btn', role: 'button'} %>
				<% else %>
				<%= link_to 'Sign up', signup_url, {class: 'btn btn-warning navbar-btn', role: 'button'} %>
				<%= link_to 'Log in', login_url, {class: 'btn btn-info navbar-btn', role: 'button'} %>
				<% end %>
			</div>
		</div>
	</div><!--/.navbar-collapse -->
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<!--
 __      __  _______  __      __
/\ \  __/\ \/\  ____\/\ \  __ \ \
\ \ \/\ \ \ \ \ \___ \ \ \ \ \ \ \
 \ \ \ \ \ \ \ \  __\ \ \ \ \ \ \ \
  \ \ \_/ \_\ \ \ \    \ \ \_/ \_\ \
   \ \___/\___/\ \_\    \ \___/\___/
    \/___//__/  \/_/     \/___//__/
-->

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Gavel</title>
  <meta name="description" content="Settle arguments.">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      padding-top: 75px;
    }
  </style>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "modernizr-2.6.2-respond-1.1.0.min" %>
</head>
<body>
<!--[if lt IE 7]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->


<%= render "layouts/navbar" %>

<div class="container" id="wrapper">

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
</div>

<%= render "layouts/footer" %>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>